const tableDataList = [
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },

    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "张三",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "李四",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "王五",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },
    {
        name: "六六",
        gender: "男",
        comment: "yes/no",
        phone: 15201225987,
        educational: "统招本科",
        jobnumver: 123,
        skill: "前端开发",
        item: "RM",
        subproject: "null",
        leads: "屈志刚",
        directleader: "屈志刚",
        status: "在职",
        region: "西安",
        site: '西安',
        aidpAccount: "屈志刚",
    },



];
module.exports = tableDataList